### ISSUE TITLE
add acknowledge parameter to configuration

### ISSUE THREAD

**Issue by endearlay** [maxam18/nginx-kafka-log-module#4]
it could be very useful to add configuration parameter for kafka **acks** = [ _0, 1, ... , all_ ]

было бы весьма полезно добавить (вынести) в конфигурационный файл (настройки плагина) параметр **acks** = [ _0, 1, ... , all_ ]

**Comment by maxam18** [comment]
**klm_log** configuration parameter options changed. You can set acknowledgement in the beginning of the topic name separated by '@' symbol. See README.

Thanks for the enhancement request!
